version: '3.9'

services:
  app:
    build: .
    environment:
      - NODE_ENV=DEVELOPMENT
    volumes:
      - .:/usr/src/app:cached
    ports:
      - '3000:3000'
    command: bash -c 'npm run dev'
