import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'

type SSRProps = {
  message: string
}

const SSR: NextPage<SSRProps> = (props) => {
  const { message } = props
  return (
    <>
      <Head>
        <title>Server Side Rendering</title>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p>This page was generated by Server Side Rendering.</p>
        <p>{message}</p>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<SSRProps> = async (context) => {
  const timestamp = new Date().toLocaleString()
  const message = `Generated: ${timestamp}.`
  return {
    props: {
      message,
    },
  }
}

export default SSR
