#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

docker compose exec -T app yarn lint:fix
docker compose exec -T app yarn lint:style
docker compose exec -T app yarn format
docker compose exec -T app yarn test
