#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

if [ "$(docker inspect --format='{{.State.Running}}' etude-next_app)" == "true" ]; then
  docker compose exec -T app yarn lint:fix
  docker compose exec -T app yarn lint:style
  docker compose exec -T app yarn format
  docker compose exec -T app yarn test
else
  yarn lint:fix
  yarn lint:style
  yarn format
  yarn test
fi
