name: Storyshots

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install deps
        run: yarn install
      - name: run build
        run: yarn build
      - name: run build storybook
        run: yarn build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
